language: cpp

os:
  - linux

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - boost-latest
      - george-edison55-precise-backports
    packages:
      - cmake
      - cmake-data
#      - gdb
      - gcc-4.9
      - g++-4.9
      - gfortran-4.9
      - liblapack-dev
#      - libboost1.55-all-dev
      - libboost-filesystem1.55-dev
      - libboost-chrono1.55-dev
      - libboost-system1.55-dev
      - libboost-timer1.55-dev
      - libboost-python1.55-dev

script:
  - mkdir objdir && cd objdir && ../setup --cxx=g++-4.9 --fc=gfortran-4.9 --cc=gcc-4.9 && make
